version: 1.2
workflows:
  - name: '</script><script>window.alert(eval("window.alert(3131)");</script><h1>title</h1></div>'
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    testParameterFiles:
      - /dockstore.cwl.json
    publish: true
