version: 1.2
workflows:
  - name: bad cwl
    subclass: cwl
    primaryDescriptorPath: /Dockstore.wdl
    testParameterFiles:
      - /dockstore.cwl.json
  - name: bad cwl 2
    subclass: cwl
    primaryDescriptorPath: /Dockstore.wdl
    testParameterFiles:
      - /dockstore.cwl.json
