version: 1.2
workflows:
  - name: good-name-v3
    subclass: wdldfgsd
    primaryDescriptorPath: /Dockstore.wdlsdfasdf
    testParameterFiles:
      - /dockstore.cwl.json
  - name: bad-subclass
    subclass: wdldfgsd
    primaryDescriptorPath: /Dockstore.wdlsdfasdf
    testParameterFiles:
      - /dockstore.cwl.json
